[package]
name = "ygopro-server"
version = "0.1.2"
edition = "2024"
license = "MIT"
authors = ["jwyxym <jwyxym@126.com>"]
description = "启动ygopro本地服务器"
keywords = ["ygopro"]
repository = "https://github.com/jwyxym/ygopro-server"

[dependencies]
ygopro = {
    git = "https://github.com/IamIpanda/ygopru",
    rev = "92ab174d5a6313d003c64cd10f6b62a7e31c4e38",
    default-features = false,
    features = ["koishi", "forge"]
}
ygopro-data = {
    git = "https://github.com/IamIpanda/ygopru",
    rev = "92ab174d5a6313d003c64cd10f6b62a7e31c4e38",
    default-features = false
}
ygopro-core-wrapper = {
    git = "https://github.com/IamIpanda/ygopru",
    rev = "92ab174d5a6313d003c64cd10f6b62a7e31c4e38",
    default-features = false,
    features = ["koishi"]
}
ygopro-handler = {
    git = "https://github.com/IamIpanda/ygopru",
    rev = "92ab174d5a6313d003c64cd10f6b62a7e31c4e38"
}
tokio = "1"
parking_lot = "0.12"
